add another implementation of lexicographical_compare_three_way
./../media/gpu/h264_rate_controller.cc:132:10: error: no matching function for call to 'lexicographical_compare_three_way'
  return std::lexicographical_compare_three_way(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../__algorithm/lexicographical_compare_three_way.h:26:16: note: candidate function template not viable: requires 5 arguments, but 4 were provided
constexpr auto lexicographical_compare_three_way(I1 f1, I1 l1, I2 f2, I2 l2, Cmp comp)
               ^
1 error generated.

Needed to pull in the version of lexicographical_compare_three_way() that
has only 4 args from clang-17 headers.