Fix arm64 FTBFS due to #including cstddef in an extern "C" block
FAILED: obj/third_party/crashpad/crashpad/util/util/signals.o
[...]
In file included from ../../third_party/crashpad/crashpad/util/posix/signals.cc:15:
In file included from ../../third_party/crashpad/crashpad/util/posix/signals.h:18:
In file included from ../../third_party/crashpad/crashpad/compat/linux/signal.h:18:
In file included from /usr/include/signal.h:316:
In file included from /usr/include/aarch64-linux-gnu/sys/ucontext.h:36:
In file included from /usr/include/aarch64-linux-gnu/sys/procfs.h:35:
In file included from ../../third_party/crashpad/crashpad/compat/linux/sys/user.h:18:
In file included from /usr/bin/../include/c++/v1/cstddef:38:
/usr/bin/../include/c++/v1/__type_traits/enable_if.h:20:1: error: templates must have C++ linkage
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/signal.h:27:1: note: extern "C" language linkage specification begins here
__BEGIN_DECLS
^
/usr/include/aarch64-linux-gnu/sys/cdefs.h:140:24: note: expanded from macro '__BEGIN_DECLS'
 # define __BEGIN_DECLS  extern "C" {
                         ^