fix wayland build issue in ANGLE
ANGLE fails to build on sid (but not bullseye) because sid's wayland
headers are newer, and:

In file included from ../../third_party/angle/src/third_party/volk/volk.h:50:
In file included from ../../third_party/vulkan-deps/vulkan-headers/src/include/vulkan/vulkan.h:41:
In file included from ../../third_party/wayland/src/src/wayland-client.h:40:
/usr/include/wayland-client-protocol.h:1040:13: error: use of undeclared identifier 'wl_proxy_marshal_flags'
pt

This needs to be fixed upstream, as the include path results in
the build using third_party/wayland/src/src/wayland-client.h
instead of /usr/include/wayland-client.h when linking against the
system's libwayland.