build fix for gcc13 on arm
In file included from ../../base/cpu.cc:5:
../../base/cpu.h:90:3: error: unknown type name 'uint8_t'
  uint8_t implementer() const { return implementer_; }
  ^
../../base/cpu.h:91:3: error: unknown type name 'uint32_t'

Since these types are surrounded by ARM #ifdefs, we didn't
catch this build failure earlier.