fix FTBFS on armel/armhf that was introduced in chromium 105
This fixes the following:
In file included from ../../third_party/blink/renderer/platform/cursors.cc:28:
../../third_party/blink/renderer/platform/wtf/std_lib_extras.h:178:29: error: unknown type name 'intptr_t'
  return !(reinterpret_cast<intptr_t>(ptr) % __alignof__(Type));

It's also been sent upstream:
https://chromium-review.googlesource.com/c/chromium/src/+/3872171